# fly.toml app configuration file generated for phonebook-with-cicd on 2024-01-02T17:53:24-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "phonebook-with-cicd"
primary_region = "iad"

[processes]
  app = "node index.js"

[build]
  [build.args]
    NODE_VERSION = "16.19.1"

[env]
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[services]
  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]