# fly.toml app configuration file generated for phonebook-with-cicd on 2024-01-02T17:53:24-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "phonebook-with-cicd"
primary_region = "iad"

[processes]
  app = "node index.js"

[build]
  [build.args]
    NODE_VERSION = "16.19.1"

[env]
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [[http_service.checks]]
  grace_period = "10s"
  interval = "1m0s"
  method = "GET"
  path = "/health"
  timeout = "5s"