# fly.toml app configuration file generated for phonebookrc on 2023-12-28T15:30:56-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "phonebookrc"
primary_region = "iad"

[deploy]
  release_command = "npm run build:ui"

[processes]
  app = "node index.js"

[env]
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]