# fly.toml app configuration file generated for phonebookrc on 2023-12-29T15:00:05-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "phonebookrc"
primary_region = "iad"

[env]
  PORT = "3001"

[processes]
  app = "node index.js"

[services]
 internal_port = 3001
 protocol = "tcp"
 [[services.ports]]
   handlers = ["http"]
   port = "80"
 [[services.ports]]
   handlers = ["tls", "http"]
   port = "443"
 [[services.ports]]
   handlers = ["tls"]
   port = "8443"
 [[services.ports]]
   handlers = ["tls"]
   port = "3001"
 [services.concurrency]
   hard_limit = 25
   soft_limit = 20
 [services.scaling]
   kind = "fixed"
   count = 1
